# Generated by Django 5.2.7 on 2025-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_a', models.CharField(blank=True, max_length=100, null=True)),
                ('name_b', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_a', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('photo_b', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('percent', models.IntegerField()),
                ('sentence', models.TextField()),
                ('tips', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
